USE db_design;
DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks`(
	`id` INT NOT NULL AUTO_INCREMENT,
    `start_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `end_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `status` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`id`)

);